# Jekyll configuration

name: ENGR-400 Lecture Series in Engineering
description: An undergraduate lecture series in engineering at the University of Wisconsin-Stout.

# url is currently only used only for the RSS feed in feed.xml
url: https://engr-400.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-106720602-1'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'engr-400'
comments: true

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge

exclude: ['README.md', 'LICENSE', 'CONTRIBUTING.md']
